### ISSUE TITLE
Support setting the execution environment

### ISSUE THREAD

**Issue by holzerch** [p1nkun1c0rns/deploy-google-cloud-run-action#135]
CloudRun provides a new second generation execution environment with full Linux compatibility ([see here](https://cloud.google.com/run/docs/about-execution-environments)).

It would be great if the action would support setting the [flag](https://cloud.google.com/sdk/gcloud/reference/run/deploy#--execution-environment)

**Comment by heubeck** [comment]
thanks for reporting.

sounds like the 2nd gen should become the standard option, WDYT?

will add the parameter soon.

**Comment by holzerch** [comment]
I think Google would first need to address the limitations about slower cold starts and memory requirements. Otherwise changing the default would be breaking for some users

**Comment by heubeck** [comment]
indeed.
I'm considering a new major version therefor.

**Comment by holzerch** [comment]
Can't you just replicate the GCP CLI behaviour? Use the platform defaults in case nothing is configured and only use a different one in case it was explicitly set?

**Comment by heubeck** [comment]
Available with https://github.com/p1nkun1c0rns/deploy-google-cloud-run-action/releases/tag/v1.16.0 and from the [`@action` ref](https://github.com/p1nkun1c0rns/deploy-google-cloud-run-action#prebuild-latest-image)
