### ISSUE TITLE
Absence of --ingress parameter

### ISSUE THREAD

**Issue by massimo-salidu-acn** [p1nkun1c0rns/deploy-google-cloud-run-action#155]
I need to add the --ingress parameter, in my case I need to limit it to internal traffic only. In general, would it not be possible to add a parameter to add extra configurations? e.g. extra_args: '--ingress=internal --another=value'

**Comment by heubeck** [comment]
Thank you for demanding.

Ingress parameter is now added with [v1.17.0](https://github.com/p1nkun1c0rns/deploy-google-cloud-run-action/releases/tag/v1.17.0) and the [latest action ref](https://github.com/p1nkun1c0rns/deploy-google-cloud-run-action#prebuild-latest-image).

Regarding the `extra_args` idea. No objection in general, but for most parameters there are default values required, that must apply in the absence of a parameter.
Example: Configuring an `ingress` value the first time will change the cloud run deployment. But removing it again would leave the cloud run deployment unchanged. For falling back to the general default, it's necessary to set `ingress` to its default `all` again, what's easiest possible with specific parameters.

Please provide feedback if it worked with your deployment, and continue to demand improvements to this action.

**Comment by massimo-salidu-acn** [comment]
The new configuration works correctly, thank you.
Regarding 'extra_args' I understand your point, misalignments may occur. In case I need new ones I will ask you :)

Best Regards,
Massimo.
