### ISSUE TITLE
Script aborts execution 

### ISSUE THREAD

**Issue by SteluHH** [p1nkun1c0rns/deploy-google-cloud-run-action#5]
We're using the script as follows in our cicd pipeline: 

    - name: Deploy Cloud Run
        id: deploy
        uses: p1nkun1c0rns/deploy-google-cloud-run-action@master
        with:
          service_account_key: ${{ secrets.GOOGLE_SERVICEACCOUNT_KEY }}
          project_id: bv2tpwbpgiyz
          gcp_region: europe-west4
          service_name: xch-checkout-calculation
          image_name: ${{ env.IMAGE }}
          image_tag: ${{ env.VERSION }}
          debug: true
        env:
          SET_ENV_DISABLE_SIGNAL_HANDLERS: jo

However when executed it simply stops here and the workflow step fails:

    /usr/bin/docker run --name d3c4e5af72a511438fa0262524b2e67b30_57201b --label 3888d3 -- 
    workdir /github/workspace --rm -e IMAGE -e VERSION -e CLOUDSDK_METRICS_ENVIRONMENT -e 
    SET_ENV_DISABLE_SIGNAL_HANDLERS -e INPUT_SERVICE_ACCOUNT_KEY -e INPUT_PROJECT_ID - 
    e INPUT_GCP_REGION -e INPUT_SERVICE_NAME -e INPUT_IMAGE_NAME -e INPUT_IMAGE_TAG -e 
    INPUT_DEBUG -e INPUT_CONCURRENCY_PER_INSTANCE -e INPUT_CPU -e INPUT_MEMORY -e 
    INPUT_MAX_INSTANCES -e INPUT_REQUEST_TIMEOUT -e INPUT_ALLOW_UNAUTHENTICATED -e 
    INPUT_SERVICE_ACCOUNT -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e 
    GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/xch-checkout-calculation-backend/xch-checkout-calculation-backend":"/github/workspace" 3888d3:c4e5af72a511438fa0262524b2e67b30

    === gcloud version ===
    Google Cloud SDK 295.0.0
    bq 2.0.57
    core 2020.05.29
    gsutil 4.51
    ======================
    + gcloud auth activate-service-account --key-file=key.json --project=bv2tpwbpgiyz
    Activated service account credentials for: [***]
    + disableDebug
    + set +x
    ++ gcloud run revisions ++ list awk '{print $2}'
    --platform=managed --project=bv2tpwbpgiyz --region=europe-west4 --service=xch-checkout- 
    calculation
    ++ grep yes
    Listed 0 items.
    + LAST_REVISION=
    + rm -f key.json

**Comment by heubeck** [comment]
Remark: It's the initial deployment, so there's no last revision of the service.

**Comment by heubeck** [comment]
This issue should be solved with https://github.com/p1nkun1c0rns/deploy-google-cloud-run-action/pull/11
Initial service deployment worked with this changes.
